package com.dr_complex.double_edged_enchantments.datagen;

import com.dr_complex.double_edged_enchantments.enchantments.DEE_Enchantments;
import net.minecraft.data.DataOutput;
import net.minecraft.data.tag.EnchantmentTagProvider;
import net.minecraft.enchantment.Enchantments;
import net.minecraft.registry.RegistryWrapper;
import net.minecraft.registry.tag.EnchantmentTags;

import java.util.concurrent.CompletableFuture;

public class DEE_EnchantmentTagProvider extends EnchantmentTagProvider {

    public DEE_EnchantmentTagProvider(DataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> completableFuture) {
        super(dataOutput, completableFuture);
    }

    @Override
    protected void configure(RegistryWrapper.WrapperLookup registries) {
        this.createTooltipOrderTag(registries,
                Enchantments.BINDING_CURSE,
                DEE_Enchantments.ENCHANTMENT_ABSORBING,
                Enchantments.VANISHING_CURSE,
                DEE_Enchantments.ENCHANTMENT_RETURN,
                Enchantments.RIPTIDE,
                DEE_Enchantments.CURSE_TIDES,
                Enchantments.CHANNELING,
                DEE_Enchantments.CURSE_CONDUCTIVENESS,
                Enchantments.WIND_BURST,
                DEE_Enchantments.CURSE_STUNNED,
                Enchantments.FROST_WALKER,
                DEE_Enchantments.CURSE_EVAPORATION,
                Enchantments.SHARPNESS,
                DEE_Enchantments.CURSE_DULLNESS,
                Enchantments.SMITE,
                DEE_Enchantments.CURSE_NECROPHOBIA,
                Enchantments.BANE_OF_ARTHROPODS,
                DEE_Enchantments.CURSE_ENTOMOPHOBIA,
                Enchantments.IMPALING,
                DEE_Enchantments.CURSE_DEEP,
                Enchantments.POWER,
                DEE_Enchantments.CURSE_SOFTNESS,
                Enchantments.DENSITY,
                DEE_Enchantments.CURSE_WEIGHTLESSNESS,
                Enchantments.BREACH,
                DEE_Enchantments.CURSE_REBUILDING,
                Enchantments.PIERCING,
                DEE_Enchantments.CURSE_REDIRECT,
                Enchantments.SWEEPING_EDGE,
                DEE_Enchantments.CURSE_NARROW,
                Enchantments.MULTISHOT,
                DEE_Enchantments.CURSE_JAMMING,
                Enchantments.FIRE_ASPECT,
                DEE_Enchantments.CURSE_ASHES,
                Enchantments.FLAME,
                DEE_Enchantments.CURSE_SMOKE,
                Enchantments.KNOCKBACK,
                DEE_Enchantments.CURSE_VACUUM,
                Enchantments.PUNCH,
                DEE_Enchantments.CURSE_HOOK,
                Enchantments.PROTECTION,
                DEE_Enchantments.CURSE_VULNERABILITY,
                Enchantments.BLAST_PROTECTION,
                DEE_Enchantments.CURSE_IMPLOSION,
                Enchantments.FIRE_PROTECTION,
                DEE_Enchantments.CURSE_FLAMMABLE,
                Enchantments.PROJECTILE_PROTECTION,
                DEE_Enchantments.CURSE_IMPALED,
                Enchantments.FEATHER_FALLING,
                DEE_Enchantments.CURSE_STONES,
                Enchantments.FORTUNE,
                DEE_Enchantments.CURSE_MISFORTUNE,
                Enchantments.LOOTING,
                DEE_Enchantments.CURSE_THIEVING,
                Enchantments.SILK_TOUCH,
                DEE_Enchantments.CURSE_LOSS,
                Enchantments.LUCK_OF_THE_SEA,
                DEE_Enchantments.CURSE_POLLUTED_OCEANS,
                Enchantments.EFFICIENCY,
                DEE_Enchantments.CURSE_FUMBLING,
                Enchantments.QUICK_CHARGE,
                DEE_Enchantments.CURSE_UNENDING,
                Enchantments.LURE,
                DEE_Enchantments.CURSE_GUARDIAN_LURE,
                Enchantments.RESPIRATION,
                DEE_Enchantments.CURSE_DROWNING,
                Enchantments.AQUA_AFFINITY,
                DEE_Enchantments.CURSE_THALASSOPHOBIA,
                Enchantments.SOUL_SPEED,
                DEE_Enchantments.CURSE_SOULLESS,
                Enchantments.SWIFT_SNEAK,
                DEE_Enchantments.CURSE_RESONATING,
                Enchantments.DEPTH_STRIDER,
                DEE_Enchantments.CURSE_UNFIT,
                Enchantments.THORNS,
                DEE_Enchantments.CURSE_IRON_MAIDEN,
                Enchantments.LOYALTY,
                DEE_Enchantments.CURSE_DECEITFULNESS,
                Enchantments.UNBREAKING,
                DEE_Enchantments.CURSE_FRAGILE,
                Enchantments.INFINITY,
                DEE_Enchantments.CURSE_CONSUMPTION,
                Enchantments.MENDING,
                DEE_Enchantments.CURSE_WORSEN,

                //all new modded content

                DEE_Enchantments.ENCHANTMENT_LUCKY,
                DEE_Enchantments.CURSE_UNLUCKY,
                DEE_Enchantments.ENCHANTMENT_CRITICALITY,
                DEE_Enchantments.CURSE_CRUELNESS,
                DEE_Enchantments.ENCHANTMENT_MOON,
                DEE_Enchantments.CURSE_JUPITER,
                DEE_Enchantments.ENCHANTMENT_AERODYNAMIC,
                DEE_Enchantments.CURSE_DRAG,
                DEE_Enchantments.ENCHANTMENT_ACCURATE,
                DEE_Enchantments.CURSE_SPREAD,
                DEE_Enchantments.NM_SHRUNKEN,
                DEE_Enchantments.NM_GROWTH,
                DEE_Enchantments.ENCHANTMENT_CLEAVING,
                DEE_Enchantments.CURSE_BLUNT,
                DEE_Enchantments.ENCHANTMENT_RANGE,
                DEE_Enchantments.CURSE_SHORTNESS,
                DEE_Enchantments.ENCHANTMENT_SPEED,
                DEE_Enchantments.CURSE_FATIGUE,
                DEE_Enchantments.ENCHANTMENT_HOPE,
                DEE_Enchantments.CURSE_DESPAIR);

        this.builder(EnchantmentTags.CURSE).add(
                Enchantments.BINDING_CURSE,
                Enchantments.VANISHING_CURSE,
                DEE_Enchantments.CURSE_TIDES,
                DEE_Enchantments.CURSE_CONDUCTIVENESS,
                DEE_Enchantments.CURSE_STUNNED,
                DEE_Enchantments.CURSE_EVAPORATION,
                DEE_Enchantments.CURSE_DULLNESS,
                DEE_Enchantments.CURSE_NECROPHOBIA,
                DEE_Enchantments.CURSE_ENTOMOPHOBIA,
                DEE_Enchantments.CURSE_DEEP,
                DEE_Enchantments.CURSE_SOFTNESS,
                DEE_Enchantments.CURSE_WEIGHTLESSNESS,
                DEE_Enchantments.CURSE_REBUILDING,
                DEE_Enchantments.CURSE_REDIRECT,
                DEE_Enchantments.CURSE_NARROW,
                DEE_Enchantments.CURSE_JAMMING,
                DEE_Enchantments.CURSE_ASHES,
                DEE_Enchantments.CURSE_SMOKE,
                DEE_Enchantments.CURSE_VACUUM,
                DEE_Enchantments.CURSE_HOOK,
                DEE_Enchantments.CURSE_VULNERABILITY,
                DEE_Enchantments.CURSE_IMPLOSION,
                DEE_Enchantments.CURSE_FLAMMABLE,
                DEE_Enchantments.CURSE_IMPALED,
                DEE_Enchantments.CURSE_STONES,
                DEE_Enchantments.CURSE_MISFORTUNE,
                DEE_Enchantments.CURSE_THIEVING,
                DEE_Enchantments.CURSE_LOSS,
                DEE_Enchantments.CURSE_POLLUTED_OCEANS,
                DEE_Enchantments.CURSE_FUMBLING,
                DEE_Enchantments.CURSE_UNENDING,
                DEE_Enchantments.CURSE_GUARDIAN_LURE,
                DEE_Enchantments.CURSE_DROWNING,
                DEE_Enchantments.CURSE_THALASSOPHOBIA,
                DEE_Enchantments.CURSE_SOULLESS,
                DEE_Enchantments.CURSE_RESONATING,
                DEE_Enchantments.CURSE_UNFIT,
                DEE_Enchantments.CURSE_IRON_MAIDEN,
                DEE_Enchantments.CURSE_DECEITFULNESS,
                DEE_Enchantments.CURSE_FRAGILE,
                DEE_Enchantments.CURSE_CONSUMPTION,
                DEE_Enchantments.CURSE_WORSEN,
                DEE_Enchantments.CURSE_UNLUCKY,
                DEE_Enchantments.CURSE_CRUELNESS,
                DEE_Enchantments.CURSE_JUPITER,
                DEE_Enchantments.CURSE_DRAG,
                DEE_Enchantments.CURSE_SPREAD,
                DEE_Enchantments.NM_GROWTH,
                DEE_Enchantments.CURSE_BLUNT,
                DEE_Enchantments.CURSE_SHORTNESS,
                DEE_Enchantments.CURSE_FATIGUE,
                DEE_Enchantments.CURSE_DESPAIR
        );

        this.builder(EnchantmentTags.ON_RANDOM_LOOT).addTag(EnchantmentTags.CURSE);
        this.builder(EnchantmentTags.ON_MOB_SPAWN_EQUIPMENT).addTag(EnchantmentTags.CURSE);
        this.builder(EnchantmentTags.ON_TRADED_EQUIPMENT).addTag(EnchantmentTags.CURSE);
        this.builder(EnchantmentTags.IN_ENCHANTING_TABLE).addTag(EnchantmentTags.CURSE);
    }
}